jobs:
- deployment: VMDeploy
  displayName: web_devops
  pool:
    vmImage: 'Ubuntu-latest'
  environment:
    name: Web_devops_VM
    resourceType: VirtualMachine
  strategy:
      runOnce:
        deploy:
          steps:
          - script: echo my first deployment
